### ISSUE TITLE
Website not visible in chromium-based browsers

### ISSUE THREAD

**Issue by kouloumos** [jonatack/jonatack.github.io#10]
I believe that after f931b2a3f72b9d43fc21c6e9e87acd4c52902ec7 the website is not displaying correctly in all browsers.
The website seems to be rendering correctly (content is there) but I'm seeing a white screen in Google Chrome, Opera and Brave. If I manually remove the newly added css it goes back to the light version. 

The website is functional and I can see the dark theme in Firefox and Safari.

**Comment by jonatack** [comment]
Thanks for letting me know! I don't allow Google on my desktop device, so I tested with Chrome only on mobile iOS, and Chrome on iOS renders the dark mode like Safari and Firefox (and the Tor Browser).

**Comment by kouloumos** [comment]
> The website seems to be rendering correctly (content is there) but I'm seeing a white screen in [...]

I just verified that this is also an issue with Chrome (latest version) on Android.

**Comment by jonatack** [comment]
Thanks for reporting. I just never use Chrome :)

Reverted the CSS change for now.
